INFO -- Device: cuda
INFO -- [92mOne dimentional problem[0m
INFO -- 
INFO -- ================================================================================
INFO -- Learning parameters
INFO -- Length:                                           [92m1.0[0m
INFO -- Total time:                                       [92m1.0[0m
INFO -- Number of points in x:                            [92m100[0m
INFO -- Number of points in initial condition:            [92m300[0m
INFO -- Weight for interior loss:                         [92m1.0[0m
INFO -- Weight for initial condition loss:                [92m0.0[0m
INFO -- Weight for boundary loss:                         [92m1.0[0m
INFO -- Layers:                                           [92m4[0m
INFO -- Neurons per layer:                                [92m20[0m
INFO -- Epochs:                                           [92m5000[0m
INFO -- Learning rate:                                    [92m0.00125[0m
INFO -- ================================================================================
INFO -- 
INFO -- Creating [92m1D[0m BSpline
INFO -- Creating PINN with [92m4[0m layers and [92m20[0m neurons per layer
INFO -- Training PINN for [93m5000[0m epochs using [93mloss_fn_weak[0m loss function
INFO -- Training interrupted at epoch [91m1[0m
ERROR -- Exception occurred: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "C:\Users\macie\Documents\Studia\Magisterka\PINN_IGA_Masters\NN_tools.py", line 45, in train_model
    loss: torch.Tensor = loss_fn(nn_approximator)
  File "C:\Users\macie\Documents\Studia\Magisterka\PINN_IGA_Masters\loss_functions.py", line 424, in compute_loss
    weight_f * interior_loss_function(model, x, t, dims=dims, test_function=test_function)
  File "C:\Users\macie\Documents\Studia\Magisterka\PINN_IGA_Masters\loss_functions.py", line 87, in interior_loss_weak
    weak = _get_loss_weak(
  File "C:\Users\macie\Documents\Studia\Magisterka\PINN_IGA_Masters\loss_functions.py", line 51, in _get_loss_weak
    + eps_interior * dfdx_model * v_deriv_x).mean() \
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
INFO -- Training took [92m1.99[0m seconds
INFO -- Creating plots and saving to files. Dimensions: 1
